"""add_lead_score_to_leads

Revision ID: 048cb7bbebc8
Revises: 4cc3ce390e46
Create Date: 2026-04-29 05:09:37.211278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '048cb7bbebc8'
down_revision: Union[str, None] = '4cc3ce390e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'lead_score')
    # ### end Alembic commands ###
